### ISSUE TITLE
Display some default channels in the Direct Messages

### ISSUE THREAD

**Issue by chamerling** [linagora/Twake#1260]
Note: This feature is inspired by Slack and other chat messaging apps.

When opening Twake for the first time, it will be nice to display a minimal list of items in the `Direct Messages` section on the sidebar.

### Direct Message 'with myself'

Automatically display the direct channel with current user. This is something users are using to save text/files/snippets...

#### TODO/TBD

- [ ] On user provisioning, create the channel
- [ ] Always keep this on top of the list?
- [ ] Do not be able to leave this channel, or to hide it
- [ ] Change the first message of the channel from `This is the first message of the channel` to something more personal...
- [ ] etc

### Bot

The day we have a chatbot, we can have it displayed in this section.
