### ISSUE TITLE
Lock features according to the pricing plan

### ISSUE THREAD

**Issue by stephanevieira75** [linagora/Twake#1333]
### TODO

- [x] #1334 Lock history according to the pricing plan
- [x] #1335 Lock guest features according to the pricing plan
- [x] #1360 Banner if there are a payment warning
- [x] #1364 Popup if there are a payment error
