### ISSUE TITLE
Generate files preview 

### ISSUE THREAD

**Issue by tissarni** [linagora/Twake#1398]
### Part 1
- [x] Find libraries to generate file preview for this kind of files:
- [x] jpg, png, tiff, etc -> Sharp
- [x] gif
- [x] svg
- [x] pdf -> Imagick (pdf-thumbnail-nodejs)
- [x] office documents (docx, doc, xls, xlsx, ppt, pptx, odp, odt, ods) -> Unoconv (unoconv-node)
- [x] Validate this libraries with @chamerling / @RomaricMourgues 

### Part 2

- [x] Fix the file upload that doesn't use resumable client library
- [x] Add libraries in docker file for node (see Note 1)
- [x] Create a MIME list to see what library supports what mime https://github.com/micnic/mime.json/blob/master/index.json
- [x] Create basic rabbitmq subscriber and pushed
- [x] Generate thumbnail in the rabbitmq "process" method

### Note 1
```
#Imagick
RUN apt-get update && apt-get install -y ghostscript && apt-get clean
RUN apt-get update && apt-get install -y libmagickwand-dev --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN pecl install imagick && docker-php-ext-enable imagick

#Unoconv
RUN apt-get update && apt-get install -y --force-yes unoconv libxml2-dev
RUN docker-php-ext-install soap
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

**Comment by RomaricMourgues** [comment]
@tissarni I updated the tasks

**Comment by chamerling** [comment]
This will be great! Looking forward to see this before holidays 😄

**Comment by chamerling** [comment]
I wrote something here https://github.com/linagora/Twake/wiki/Preview-service
