### ISSUE TITLE
Marketing popups

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1458]
- [x] #1455 Popup if the user want to create a workspace -> eahc time we click on "Create workspace" button
- [x] #1457 Popup for onlyoffice -> It will appear for any "edit" buttons click

TO DEFINE
- [ ] #1456 Popup if the user reached the drive limit -> On peut pas mettre le feature flipping now
