### ISSUE TITLE
Re-implement the "is writing" event

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#1811]
**Functional**

Add a small text with the names of the currently writing users under the list of messages (in channel and in thread view):
- Version with two users: "Romaric, Benoit are writing..."
- Version with one user: "Romaric is writing..."

We can have a little animation but not too much, we cannot have a bubble like in messenger because the design is too different (we can take inspiration from discord, slack and teams).

The channel should have a little writing icon when someone is writing in it on the channel bar.

**Technical detail**

This realtime event will goes through the workspace websocket room (this will allow us to see the channel being edited in realtime and prepare for the call system update later).

**Tasks**

- [ ] Create an atomFamily named "ChannelWritingActivityState" with family key "channelId" and value `{threadId, userId, name, isWriting: boolean}[]`
- [ ] Create a selector to listen to only a threadId
- [ ] Create a useChannelWritingActivity(channelId, threadId: string | null) => {users: {userId, name}[], iAmWriting: Function}
